<?php
/**
 * Content left facets template
 *
 * @var $block \Klevu\Content\Block\Index
 */
?>
<?php $contentFilters = $block->getContentFilters();
$queryParam = $block->getQueryParam(); ?>
<?php if (count($contentFilters)> 0): ?>
<div class="col-left-first">
   <div class="block block-layered-nav">
    <div class="block-content toggle-content">
         <dl id="narrow-by-list">
            <dt class="odd"><?php /* @escapeNotVerified */ echo __("Type"); ?></dt>
            <dd class="odd">
               <ol>
                    <?php foreach ($contentFilters["category"]["options"] as $key => $value): ?>
                    <?php $url_content = $block->getUrl('content/search', ["q" => $queryParam]); ?> 
					<?php $label = $value["label"]; ?>					
                    <li class="kuFilterSelect">
                        <a href="<?php /* @escapeNotVerified */ echo $url_content."?cat=".strtolower($block->escapeHtml($label));?>" class="kuFilterLbl">
                            <?php echo $block->escapeHtml($label); ?><span class="count"> (<?php /* @escapeNotVerified */ echo $value["count"]; ?>)</span>
                            
                        </a>
                        <?php if ($value["selected"]=="true") { ?>
                              <a href="<?php /* @escapeNotVerified */ echo $url_content;?>" class="kuFilterClose">X</a>
                        <?php } ?>
                    </li>
                    <div class="kuClrFilterBoth"></div>
					<?php endforeach; ?>              
               </ol>
            </dd>             
         </dl>
      </div>
   </div>
</div>
<?php endif; ?>
