<?php
/**
 * Content template for KLEVU CMS variables
 *
 * @var $block \Klevu\Content\Block\QueryType
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$isCmsSyncEnabledOnFront = $block->isCmsSyncEnabledOnFront()
    ? 'true'
    : 'false';
?>

<?php if ($block->isExtensionConfigured()): ?>
    <?= $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        'var klevu_cms_module_enabled = true;',
        true
    ) ?>
<?php endif; ?>

<?php
$scriptString = <<<script

    var klevu_cmsSearchEnabled = {$isCmsSyncEnabledOnFront};

script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    true
) ?>
